kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
